[master] support public readonly properties, fixes #27
brick/varexporter pull request #28
Opened 2022-12-08 20:07 UTC by AnnaDamm

See #27

2022-12-09 09:50 UTC, func0der approved these changes

2022-12-09 12:03 UTC, pascalheidmann approved these changes

2022-12-16 10:19 UTC, AnnaDamm commented
@BenMorel Could you have a look at this PR, please? :-)

2022-12-23 14:10 UTC, BenMorel requested changes
Thank you for this PR! 🫶

2022-12-23 14:10 UTC, BenMorel commented on tests/Classes/PublicReadonlyPropertiesWithConstructor.php
> +class PublicReadonlyPropertiesWithConstructor
Shouldn't this be:

```suggestion
class ReadonlyPropertiesWithConstructor
```

As you have private readonly as well?

2023-01-06 11:15 UTC, BenMorel commented
@AnnaDamm Do you have time to apply suggestions? Do you want me to take over?

2023-01-06 11:43 UTC, AnnaDamm commented on src/Internal/ObjectExporter/AnyObjectExporter.php
> +            $publicOrReadonlyProperties = [];
It is possible to have private readonly properties (check the test case for that), so they don't have to be public. That is why I chose "or"

2023-01-06 11:46 UTC, AnnaDamm commented on src/Internal/ObjectExporter/AnyObjectExporter.php
> +            $publicOrReadonlyProperties = [];
Yes you are right

2023-01-06 11:47 UTC, AnnaDamm commented
Hey @BenMorel! Sorry, I have been on vacation over the past 2 weeks and will be able to change the PR next week

2023-01-21 23:02 UTC, merged

2023-01-21 23:02 UTC, BenMorel commented
Thank you, @AnnaDamm !

2023-01-21 23:07 UTC, BenMorel commented
Released as [0.3.8](https://github.com/brick/varexporter/releases/tag/0.3.8).